### ISSUE TITLE
Update README to say how to deploy the pre-built images?

### ISSUE THREAD

**Issue by shabiel** [KRMAssociatesInc/docker-vista#1]
I don't know how I made it run in the end, but it wasn't obvious.

TIA, --Sam

**Comment by ChristopherEdwards** [comment]
README updated. Please comment if more changes are necessary.

**Comment by bschreib** [comment]
Hi.  Once I have my docker container up and running, how do I get EWD running within it?  Thanks.

**Comment by ChristopherEdwards** [comment]
@bschreib I haven't fixed the automation for EWD.js/QEWD yet. There is code there that needs to be modified to work with the new frameworks, just haven't done it yet.

**Comment by ChristopherEdwards** [comment]
@bschreib QEWD support has been added. see latest commits.
